### ISSUE TITLE
Дефолтные значения

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Resume#12]
**competence-list-item.pug**
![1](https://user-images.githubusercontent.com/19621113/71322098-80c0b100-24d4-11ea-8c49-dabb10372b6a.png)

В случаях, когда у тебя для всех параметров заданы значения по умолчанию, целесообразно для самого деструктурированного объекта параметров также задать дефолтное значение в виде пустого объекта `{}`, чтобы можно было вызывать миксин вообще без аргументов

**Comment by Nelliza** [comment]
И еще, разбей пожалуйста деструктурированный объект по строкам, как я сделала у тебя в примере выше, а то получается слишком длинная строка

**Comment by DenisKhodasevich** [comment]
> И еще, разбей пожалуйста деструктурированный объект по строкам, как я сделала у тебя в примере выше, а то получается слишком длинная строка

Когда я пытаюсь так сделать, у меня код не компилируется, появляется вот такая ошибка
![Снимок экрана от 2019-12-22 23-54-46](https://user-images.githubusercontent.com/43818614/71326567-74614600-251e-11ea-8249-5b0a7fc9a832.jpg)

**Comment by Nelliza** [comment]
Да, прости, я совсем забыла, что pug чувствителен к переносам строк )
В таком случае меньшим из зол, как мне кажется, будет вынесение ключа `text` с дефолтным значением на отдельную строку, вот так:
![1](https://user-images.githubusercontent.com/19621113/71423670-017dd980-269c-11ea-9533-6247b00a5c37.png)
