### ISSUE TITLE
Дублирующийся код

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Resume#2]
**index.pug**
![2](https://user-images.githubusercontent.com/19621113/70560328-7380f980-1b99-11ea-97f0-9663422b1433.png)
Вот здесь у тебя абсолютно дублирующийся код, и дальше при вызове миксина `experience` ровно та же ситуация. Это не очень нецелесообразная реализация, нужно стараться по максимуму избавляться от дублей в коде

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/70961017-b6f3d000-2091-11ea-8733-e3a79f005512.png)

Вот этот кусок кода я бы чуть упростила:
![2](https://user-images.githubusercontent.com/19621113/70961129-fb7f6b80-2091-11ea-88e4-193f3fbe837b.png)

**Comment by Nelliza** [comment]
И хотела уточнить, какой смысл несет в себе вот этот код здесь и в **education.pug**:
`- const {} = item;`

**Comment by DenisKhodasevich** [comment]
Удалил эту строку из обоих блоков, смысла в ней нет. Там сначала была деструктуризация объекта, потом, когда я перестал передавать свойства при вызове этих миксинов, у меня код не компилировался, и я, вместо того, чтобы просто удалить эту строку, удалил только сами свойства.
