### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Resume#4]
![1](https://user-images.githubusercontent.com/19621113/70561234-26058c00-1b9b-11ea-9bd3-1b12bc021207.png)
У меня не сходится PerfectPixel, скинь сюда пожалуйста скрин макета с наложенным PerfectPixel (желательно в инверсии) и открытым окошком его настроек, как у меня

**Comment by DenisKhodasevich** [comment]
У меня всё точно так же, я специально так оставил, потому что макет не очень пропорциональный, и там правые блоки немного выше, чем левые, а я задал им одинаковый отступ. Если так не пойдёт, то могу сделать, как в макете.

**Comment by Nelliza** [comment]
Ок, я уточню этот момент тогда и напишу

**Comment by Znack** [comment]
В целом макет действительно кривой, но хотя бы основные параметры должны совпадать. Конкретно для резюме можно забить, в новом макете Toxin это уже получше. Да и для UI kit пиксель перфект гораздо легче и важнее сделать

**Comment by Nelliza** [comment]
Тогда закрываю ишью )
